# Generated by Django 5.0.3 on 2024-03-29 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_customer_age_alter_customer_total_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 29, 13, 37, 2, 587214)),
        ),
    ]
